// Code initially generated by protoc-gen-grpc-impl
package examples

import (
	"context"

	"github.com/golang/protobuf/ptypes/empty"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// BookstoreFuncs is an implementation of the grpc-defined type, Bookstore.
// Its members are functions which implement the defined rpc endpoints.
type BookstoreFuncs struct {
	ListShelvesMethod func(ctx context.Context, input *empty.Empty) (*ListShelvesResponse, error)

	CreateShelfMethod func(ctx context.Context, input *CreateShelfRequest) (*Shelf, error)

	GetShelfMethod func(ctx context.Context, input *GetShelfRequest) (*Shelf, error)

	DeleteShelfMethod func(ctx context.Context, input *DeleteShelfRequest) (*empty.Empty, error)

	ListBooksMethod func(ctx context.Context, input *ListBooksRequest) (*ListBooksResponse, error)

	CreateBookMethod func(ctx context.Context, input *CreateBookRequest) (*Book, error)

	GetBookMethod func(ctx context.Context, input *GetBookRequest) (*Book, error)

	DeleteBookMethod func(ctx context.Context, input *DeleteBookRequest) (*empty.Empty, error)
}

// ListShelves calls the provided implementation, ListShelvesMethod.
func (t *BookstoreFuncs) ListShelves(ctx context.Context, input *empty.Empty) (*ListShelvesResponse, error) {
	return t.ListShelvesMethod(ctx, input)
}

// CreateShelf calls the provided implementation, CreateShelfMethod.
func (t *BookstoreFuncs) CreateShelf(ctx context.Context, input *CreateShelfRequest) (*Shelf, error) {
	return t.CreateShelfMethod(ctx, input)
}

// GetShelf calls the provided implementation, GetShelfMethod.
func (t *BookstoreFuncs) GetShelf(ctx context.Context, input *GetShelfRequest) (*Shelf, error) {
	return t.GetShelfMethod(ctx, input)
}

// DeleteShelf calls the provided implementation, DeleteShelfMethod.
func (t *BookstoreFuncs) DeleteShelf(ctx context.Context, input *DeleteShelfRequest) (*empty.Empty, error) {
	return t.DeleteShelfMethod(ctx, input)
}

// ListBooks calls the provided implementation, ListBooksMethod.
func (t *BookstoreFuncs) ListBooks(ctx context.Context, input *ListBooksRequest) (*ListBooksResponse, error) {
	return t.ListBooksMethod(ctx, input)
}

// CreateBook calls the provided implementation, CreateBookMethod.
func (t *BookstoreFuncs) CreateBook(ctx context.Context, input *CreateBookRequest) (*Book, error) {
	return t.CreateBookMethod(ctx, input)
}

// GetBook calls the provided implementation, GetBookMethod.
func (t *BookstoreFuncs) GetBook(ctx context.Context, input *GetBookRequest) (*Book, error) {
	return t.GetBookMethod(ctx, input)
}

// DeleteBook calls the provided implementation, DeleteBookMethod.
func (t *BookstoreFuncs) DeleteBook(ctx context.Context, input *DeleteBookRequest) (*empty.Empty, error) {
	return t.DeleteBookMethod(ctx, input)
}

// Register associates the implementation with a grpc server.
func (t *BookstoreFuncs) Register(srv *grpc.Server) {
	RegisterBookstoreServer(srv, t)
}

// NewBookstoreFuncs creates an instance of Bookstore with unimplemented method stubs.
// NOTE: you should provide your own functions which implement the underlying methods.
func NewBookstoreFuncs() *BookstoreFuncs {
	var t = new(BookstoreFuncs)

	t.ListShelvesMethod = func(ctx context.Context, input *empty.Empty) (*ListShelvesResponse, error) {
		return nil, status.Errorf(codes.Unimplemented, "ListShelves has not been implemented")
	}

	t.CreateShelfMethod = func(ctx context.Context, input *CreateShelfRequest) (*Shelf, error) {
		return nil, status.Errorf(codes.Unimplemented, "CreateShelf has not been implemented")
	}

	t.GetShelfMethod = func(ctx context.Context, input *GetShelfRequest) (*Shelf, error) {
		return nil, status.Errorf(codes.Unimplemented, "GetShelf has not been implemented")
	}

	t.DeleteShelfMethod = func(ctx context.Context, input *DeleteShelfRequest) (*empty.Empty, error) {
		return nil, status.Errorf(codes.Unimplemented, "DeleteShelf has not been implemented")
	}

	t.ListBooksMethod = func(ctx context.Context, input *ListBooksRequest) (*ListBooksResponse, error) {
		return nil, status.Errorf(codes.Unimplemented, "ListBooks has not been implemented")
	}

	t.CreateBookMethod = func(ctx context.Context, input *CreateBookRequest) (*Book, error) {
		return nil, status.Errorf(codes.Unimplemented, "CreateBook has not been implemented")
	}

	t.GetBookMethod = func(ctx context.Context, input *GetBookRequest) (*Book, error) {
		return nil, status.Errorf(codes.Unimplemented, "GetBook has not been implemented")
	}

	t.DeleteBookMethod = func(ctx context.Context, input *DeleteBookRequest) (*empty.Empty, error) {
		return nil, status.Errorf(codes.Unimplemented, "DeleteBook has not been implemented")
	}

	return t
}
